#!/bin/env bash

# DEPENDENCIES:
# - mpv       https://mpv.io/
# - termdown  https://github.com/trehn/termdown
#
# install: 
# pip3 install termdown && sudo dnf install mpv

##################################################

# Sleep duration, in minutes. If you want to dynamically
# change it, input the new duration as the first argument
# to this script.
sleepduration=30

# A list of musics from which one will be randomly selected
# to be played while you are sleeping.
sleep_musics=(
	"https://youtu.be/XP1O2eWA84s"
	"https://youtu.be/Fu04bfwn1PU?si=xn5qEwsyv6aGon3m"
)
# A list of music from which one will be 
# randomly selected to wake you up.
wake_up_musics=(
	"https://youtu.be/Inz9OOVh7dg"
)

# You should not have to modify this, but it is pretty
# self explanatory.
# Float (-1 to 1000) (base volume is 100.000 (100%))
sleepvolume=70
wakeupvolume=140

##################################################

sleepmusic=${sleep_musics[$(($RANDOM%${#sleep_musics[@]}))]}
wakeupmusic=${wake_up_musics[$(($RANDOM%${#wake_up_musics[@]}))]}


if [[ $1 != "" ]]; then
	sleepduration=$1
fi

pidfile="/tmp/dodopid"
mpv --no-video $sleepmusic --volume=$sleepvolume --no-terminal & echo $! > $pidfile
termdown "${sleepduration}mn" -W -e -s

if test -f $pidfile; then
	kill $(head $pidfile)
	rm $pidfile
fi

mpv --no-video $wakeupmusic --volume=$wakeupvolume
